/*
 * File: app/com/ui/XdfnViewport.js
 * Date: Tue Oct 11 2011 16:37:33 GMT+0800 (ÖÐ¹ú±ê×¼Ê±¼ä)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('xdfn.com.ui.XdfnViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;
        me.items = [
            {
                xtype: 'panel',
                border: 0,
                height: 61,
                html: '<div id="MainHead"><div id="XDFN"><img src="resources/images/xdfn2.png" height="57" /></div><div id="SysMenu"><div id="DatetimeView"><div id="DateStr"><ul><li id="DateId"></li><li id="WeekId"></li></ul></div><div id="LoginInfo"><ul><li id="TimeId">8:30:30</li><li id="WelcomeId"></li></ul></div></div><div id="Logout"><ul><li>退出</li><li><a  id="ExitSysId" href="#" title="退出系统"></a></li></ul><ul><li>帮助</li><li><a  id="HelpId" href="#" title="帮助"></a></li></ul></div></div></div>',
                id: 'xdfnHead',
                activeItem: 0,
                layout: {
                    type: 'absolute'
                },
                title: '',
                region: 'north'
            },
            {
                xtype: 'panel',
                id: 'xdfnMenu',
                width: 218,
                layout: {
                    type: 'accordion'
                },
                collapsible: true,
                iconCls: 'nav',
                title: '系统选择菜单',
                titleCollapse: true,
                region: 'west',
                split: true,
                items: [
                    {
                        xtype: 'panel',
                        layout: {
                            type: 'fit'
                        },
                        collapsed: false,
                        iconCls: 'nav',
                        title: '个人平台',
                        items: [
                            {
                                xtype: 'treepanel',
                                id: 'PersonPadTree',
                                root: {
                                    expended: true,
                                    children: [
                                        {
                                            text: '个人平台',
                                            leaf: true
                                        },
                                        {
                                            text: '个人信息',
                                            leaf: true
                                        },
                                        {
                                            text: '个人日程',
                                            leaf: true
                                        },
                                        {
                                            text: '通讯录',
                                            leaf: true
                                        }
                                    ]
                                },
                                rootVisible: false
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            type: 'fit'
                        },
                        collapsed: true,
                        iconCls: 'nav',
                        title: '信息中心',
                        items: [
                            {
                                xtype: 'treepanel',
                                id: 'InfoCenterTree',
                                root: {
                                    expended: true,
                                    children: [
                                        {
                                            text: '公告栏',
                                            leaf: true
                                        },
                                        {
                                            text: '最新资讯',
                                            leaf: true
                                        }
                                    ]
                                },
                                rootVisible: false
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            type: 'fit'
                        },
                        collapsed: true,
                        iconCls: 'nav',
                        title: '项目管理',
                        items: [
                            {
                                xtype: 'treepanel',
                                id: 'ProjectMgrTree',
                                root: {
                                    expended: true,
                                    children: [
                                        {
                                            text: '项目总览',
                                            leaf: true
                                        },
                                        {
                                            text: '项目审核',
                                            leaf: true
                                        },
                                        /*{
                                            text: '项目统计',
                                            leaf: true
                                        },*/
                                        {
                                            text: '合同管理',
                                            leaf: true
                                        },
                                        {
                                            text: '回款管理',
                                            leaf: true
                                        },
                                        {
                                            text: '执行管理',
                                            leaf: true
                                        }
                                    ]
                                },
                                rootVisible: false
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            align: 'stretch',
                            type: 'vbox'
                        },
                        collapsed: true,
                        hidden: true,
                        iconCls: 'nav',
                        title: '合同管理',
                        items: [
                            {
                                xtype: 'treepanel',
                                id: 'ContractMgrTree',
                                root: {
                                    expended: true,
                                    children: [
                                        {
                                            text: '合同签订预报',
                                            leaf: true
                                        },
                                        {
                                            text: '合同记录管理',
                                            leaf: true
                                        }
                                    ]
                                },
                                rootVisible: false,
                                flex: 1
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            type: 'fit'
                        },
                        collapsed: true,
                        hidden: true,
                        iconCls: 'nav',
                        title: '回款管理',
                        items: [
                            {
                                xtype: 'treepanel',
                                height: 250,
                                id: 'MoneyMgrTree',
                                width: 400,
                                root: {
                                    expended: true,
                                    children: [
                                        {
                                            text: '合同回款计划',
                                            leaf: true
                                        },
                                        {
                                            text: '回款指标及计划',
                                            leaf: true
                                        },
                                        {
                                            text: '回款完成记录',
                                            leaf: true
                                        }
                                    ]
                                },
                                rootVisible: false
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            type: 'fit'
                        },
                        hidden: true,
                        collapsed: true,
                        iconCls: 'nav',
                        title: '执行管理',
                        items: [
                            {
                                xtype: 'treepanel',
                                height: 250,
                                id: 'ExecMgrTree',
                                width: 400,
                                root: {
                                    expended: true,
                                    children: [
                                        {
                                            text: '发货记录',
                                            leaf: true
                                        },
                                        {
                                            text: '排产记录',
                                            leaf: true
                                        },
                                        {
                                            text: '合同执行期文档管理',
                                            leaf: true
                                        },
                                        {
                                            text: '风机安装进度表',
                                            leaf: true
                                        }
                                    ]
                                },
                                rootVisible: false
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            type: 'fit'
                        },
                        collapsed: true,
                        iconCls: 'nav',
                        title: '服务管理',
                        items: [
                            {
                                xtype: 'treepanel',
                                height: 250,
                                id: 'ServiceMgrTree',
                                width: 400,
                                root: {
                                    expended: true,
                                    children: [
                                        {
                                            text: '服务记录',
                                            leaf: true
                                        },
                                        {
                                            text: '传真管理',
                                            leaf: true
                                        }
                                    ]
                                },
                                rootVisible: false
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            type: 'fit'
                        },
                        collapsed: true,
                        iconCls: 'nav',
                        title: '客户管理',
                        items: [
                            {
                                xtype: 'treepanel',
                                height: 250,
                                id: 'CustomerMgrTree',
                                width: 400,
                                root: {
                                    expended: true,
                                    children: [
                                        {
                                            text: '客户信息',
                                            leaf: true
                                        },
                                        {
                                            text: '客户接待',
                                            leaf: true
                                        }
                                    ]
                                },
                                rootVisible: false
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            type: 'fit'
                        },
                        collapsed: true,
                        iconCls: 'nav',
                        title: '系统管理',
                        items: [
                            {
                                xtype: 'treepanel',
                                height: 250,
                                id: 'SysMgrTree',
                                width: 400,
                                root: {
                                    expended: true,
                                    children: [
                                        {
                                            text: '员工管理',
                                            leaf: true
                                        },
                                        {
                                            text: '权限管理',
                                            leaf: true
                                        },
                                        {
                                            text: '发布公告',
                                            leaf: true
                                        },
                                        {
                                            text: '发布资讯',
                                            leaf: true
                                        }
                                    ]
                                },
                                rootVisible: false
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                id: 'xdfnTabPanel',
                layout: {
                    type: 'fit'
                },
                region: 'center',
                activeTab: 0,
                bodyStyle: 'border:0px'
            },
            {
                xtype: 'toolbar',
                height: 32,
                region: 'south',
                items: [
                    {
                        xtype: 'tbtext',
                        text: 'Copyright &copy; 湘电风能有限公司 2012'
                    },
                    {
			            xtype: 'tbfill'
			        },
			        {
			            xtype: 'splitbutton',
			            text: '功能',
			            menu: {
			                xtype: 'menu',
			                width: 120,
			                items: [
			                    {
			                        xtype: 'menucheckitem',
			                        text: '隐藏系统栏',
			                        handler: function() {
			                        	var h = Ext.getCmp('xdfnHead');
			                        	if (!h.isHidden()) {
			                        	    h.hide();
			                        	}
			                        	else {
			                        	    h.show();
			                        	}
			                        }
			                    }
			                ]
			            }
			        }
                ]
            }
        ];
        me.callParent(arguments);
    }
});